version: '3'
services:
  db:
    image: "mysql:5.6"
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  builder:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../target:/wheelhouse
      - cache
      - build:/build
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build", "."]

  agent:
    image: seyio/ansible
    volumes:
      - /home/vagrant/cd-docker-ansible/todobackend/ansible/probe.yml:/ansible/site.yml
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"

  tshoot:
    image: ubuntu:trusty
    volumes:
      - cache:/cache
      - build:/build
    command: ["ls", "/build"]

  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    image: todobackend-dev
    volumes:
      - cache:/cache
      - build:/build
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports

#  cache:
#    build:
#      context: ../../
#      dockerfile: docker/dev/Dockerfile
#    volumes:
#      - /tmp/cache:/
volumes:
  cache: 
  build:
