version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
    volumes:
      - webroot:/var/www/todobackend
    links:
      - db
    environment:
      DJANGO_SETTING_MODULE: todobackend.settings.release
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
    command:
      - uwsgi
      - "--socket /var/www/todobackend/todobackend.sock"
      - "--chmod-socket=666"
      - "--module todobackend.wsgi"
      - "--master"
      - "--die-on-term"

  nginx:
    image: nginx
    volumes:
      - ./todobackend.conf:/etc/nginx/conf.d/todobackend.conf
    links:
      - app
    ports:
      - "80:8000"
    volumes:
      - webroot:/var/www/todobackend

  db:
    image: "mysql:5.6"
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: todobackend
      MYSQL_USER: todo
      MYSQL_PASSWORD: pa55word
      MYSQL_ROOT_PASSWORD: pa55wor0

  agent:
    image: seyio/ansible
    volumes:
      - /home/vagrant/cd-docker-ansible/todobackend/ansible/probe.yml:/ansible/site.yml
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"

volumes:
  webroot:
